// Navigation functions
function navigateToInput() {
    window.location.href = 'input.html';
}

function navigateToRoadmap() {
    window.location.href = 'roadmap.html';
}

function navigateToWeekDetail(weekNumber) {
    window.location.href = `week-detail.html?week=${weekNumber}`;
}

function goBack() {
    window.history.back();
}

// Generate roadmap based on user input
function generateRoadmap() {
    const domain = document.getElementById('domain').value;
    const level = document.getElementById('level').value;
    const timeline = document.getElementById('timeline').value;
    const goals = document.getElementById('goals').value;

    // Basic validation
    if (!domain || !level || !timeline) {
        alert('Please fill in all required fields');
        return;
    }

    // Store user input in localStorage for the roadmap page
    const userData = {
        domain,
        level,
        timeline,
        goals,
        generatedAt: new Date().toISOString()
    };
    
    localStorage.setItem('liaaUserData', JSON.stringify(userData));
    
    // Navigate to roadmap page
    navigateToRoadmap();
}

// Generate sample weeks for demonstration
function generateWeeks() {
    const weeksGrid = document.getElementById('weeksGrid');
    const totalWeeks = 12;
    
    const weekTitles = [
        "HTML & CSS Fundamentals",
        "JavaScript Basics",
        "DOM Manipulation",
        "Advanced JavaScript",
        "React Introduction", 
        "React Components & Props",
        "React State & Hooks",
        "React Router & APIs",
        "Backend Basics with Node.js",
        "Database Integration",
        "Project Development",
        "Deployment & Optimization"
    ];
    
    for (let i = 1; i <= totalWeeks; i++) {
        const weekCard = document.createElement('div');
        weekCard.className = 'week-card';
        weekCard.onclick = () => navigateToWeekDetail(i);
        
        weekCard.innerHTML = `
            <h3>Week ${i}: ${weekTitles[i-1]}</h3>
            <p>${getWeekDescription(i)}</p>
            <div class="week-progress">
                <span>Click to view details →</span>
            </div>
        `;
        
        weeksGrid.appendChild(weekCard);
    }
}

function getWeekDescription(weekNumber) {
    const descriptions = {
        1: "Learn the building blocks of web development with HTML structure and CSS styling.",
        2: "Master JavaScript fundamentals including variables, functions, and control flow.",
        3: "Learn to manipulate web page content dynamically using JavaScript.",
        4: "Dive into advanced JavaScript concepts like ES6+ features and async programming.",
        5: "Get introduced to React library and understand component-based architecture.",
        6: "Learn about React components, props, and component composition.",
        7: "Master state management and React hooks for dynamic applications.",
        8: "Learn routing and API integration in React applications.",
        9: "Introduction to backend development with Node.js and Express.",
        10: "Learn database integration with MongoDB and data modeling.",
        11: "Apply all concepts to build a complete full-stack application.",
        12: "Learn deployment strategies and performance optimization techniques."
    };
    
    return descriptions[weekNumber] || "Weekly learning objectives and tasks.";
}

// Share functionality
function shareRoadmap() {
    if (navigator.share) {
        navigator.share({
            title: 'My Learning Roadmap - LIAA',
            text: 'Check out my personalized learning roadmap generated by LIAA!',
            url: window.location.href
        });
    } else {
        alert('Share functionality not supported in your browser. Copy the URL manually.');
    }
}

// Load user data on roadmap page
document.addEventListener('DOMContentLoaded', function() {
    if (window.location.pathname.includes('roadmap.html')) {
        const userData = JSON.parse(localStorage.getItem('liaaUserData') || '{}');
        
        // Update roadmap header with user data
        const roadmapHeader = document.querySelector('.roadmap-header h2');
        if (roadmapHeader && userData.domain) {
            roadmapHeader.textContent = `Your ${userData.domain} Roadmap`;
        }
    }
});
